name: Linux Tests

on:
  push:
    branches: [main, "[0-9]+.[0-9]+.x"]
  pull_request:
  schedule:
    - cron: "0 10 * * *" # runs at 10:00 UTC (03:00 PST) every day
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, cpu]

    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]

    name: Python ${{ matrix.python }} integration

    env:
      PYTHON: ${{ matrix.python }}
      RUNNER_WORKDIR: ${{ vars.RUNNER_WORKDIR_BASE || '/mnt/workdir' }}/gsMap-${{ github.workflow }}-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.python }}
      TEST_DATA_DIR: /gsmap_test_data

    steps:
      - name: Create unique workdir
        run: |
          mkdir -p $RUNNER_WORKDIR
          echo "Created workdir: $RUNNER_WORKDIR"

      - uses: actions/checkout@v4
        with:
          path: ${{ env.RUNNER_WORKDIR }}/gsMap

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        working-directory: ${{ env.RUNNER_WORKDIR }}/gsMap
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pytest pytest-cov
          python -m pip install -e .[doc]

      - name: Run pytest
        working-directory: ${{ env.RUNNER_WORKDIR }}/gsMap
        env:
          MPLBACKEND: agg
          DISPLAY: :42
          COLUMNS: 120
        run: |
          python -m pytest --cov=src --cov-report=term-missing -v -s --color=yes \
            --cov-report=xml --run-real-data \
            --work-dir=${{ env.RUNNER_WORKDIR }}/workdir \
            --test-data=${{ env.TEST_DATA_DIR }}
          
          # Generate HTML report for viewing
          python -m pytest --cov=src --cov-report=html --cov-config=.coveragerc

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.RUNNER_WORKDIR }}/gsMap/coverage.xml
          fail_ci_if_error: false

      - name: Retain test results
        if: always()
        run: |
          echo "Test results are stored in $RUNNER_WORKDIR"
          # Create a summary file with metadata
          echo "Test run completed at $(date)" > $RUNNER_WORKDIR/test-summary.txt
          echo "Workflow: ${{ github.workflow }}" >> $RUNNER_WORKDIR/test-summary.txt
          echo "Run ID: ${{ github.run_id }}" >> $RUNNER_WORKDIR/test-summary.txt
          echo "Run Number: ${{ github.run_number }}" >> $RUNNER_WORKDIR/test-summary.txt
          echo "Python Version: ${{ matrix.python }}" >> $RUNNER_WORKDIR/test-summary.txt
          echo "Repository: ${{ github.repository }}" >> $RUNNER_WORKDIR/test-summary.txt
          echo "Ref: ${{ github.ref }}" >> $RUNNER_WORKDIR/test-summary.txt